---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "pkNmzMQfIy4aWC8IOXevLpFujPNlBdbdZeiR7dLG7E7xsC1ltjbK2EH17i/bztLGdmR4leMVn0UY67jH3z4ZPg8chZUcVEhoKIHdqlOo098nbOEfQ7gdz5cKtfjxhQYkk7BJjaMqZyRayFS3ouesp1yVirmv/hhdN/Anl7CmjkXcZsXznaQaFNIBpAW/HSIos624am0jfTUx5mcfHPFMYBYTlg/S1P+vADJ3O7uHu4YfwCyROMG8c0stCkAQ+KmGQCihNz76U4lNnQNi/Hv2MGiki3mSi0dY9+/sD2Sc+Nmt3TcHQvW2q5L6NDixkxNsAM3D3pJs1W+nUOwdIJNOIo4wLndw2X+GByQmTOBcu6rqVaHLNXGDDkvlfBweF03nCMs8r5Vz2tGhAiODQw0zYu23K/A+YbtR5E9f+76KOyTDttvd0fYAUB8mB8YsUkr9O4B5WNCoQVu2Y+faQg6zcWtCMrk2fqJ9v5ZYnvLlA+HQUGfnsDfSzMCh3GnKkq2yzWy+wabH87nTuK2eNlCTE1gNisdYzDfDwHQTdB20lnX2zLOWgUXydbyjsq68ZTnI8yIhuCGPGb00WC2Ybf+KFohzpOav1xKaD2L5rqtJq4ofjKU4IVCpvj9dn4wK9hBlW5wFsPh6hBcSKVKImzt/vhsh7wDiAgpiUy1zaHprcQo="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
