---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "TDftZCQhXv5nEbyxTagsf8ZgsXWi0NjW1DZv9tDNrBWtRIaspn0YfYkGfeJi5zVs5fbwj/eQ7A+BUhw/6iZgMQHLEXjGuNDDw4dVQIoh0SG8m7gs/31XzQaSrycuNI0dDJiSyPFqo7wx7/FKxTyU60Uk29sMmxs9jcxNdvIbVIXtoITPNA+xf7A4yKM6mA2HLB6pDi6ygMC/yg9vzD6M1V97tF5vx1w3Tqs9VeJExDVaRXoWlbLB2PRdOKTciCV7PqiwNkvAoxYFMdbrYxXwT3k6H/FHneQqv0gxTBJHMvDJSysirPbo7Qc+E/VZogUaclQl7kFPzlw23jlOo2IQ4mBIbxi9y2DSW0xgeGHbvMepLFHUSO0oyqCb2VYgGpFzTUUjyg4xFB6uGH2bqsRXg8KEGoWxnhZ0ZYIO8Ucc/ea22WTPZGEI6tyLGiQ9kuZXSdNo5L5qMomPWuHDoTzVvr2FVfI0bd0jztqq74ExYgq7a2gNif8j/HejS7/MCn4Qb4jEkXEHye2EP5T3k166+et4HetMh8fafTS2NI9kB3LK3GFPB3+19/pPaDYtAdofECi/vQg6Pb7LNSF9/MQnCULDSg8QfD98d6acblFuySZqJuB5sYkyA8aYW2oIiu8HT3EuASj7sLQCAWb2MfylG6wYcmfxkMXrp3S5cnbv1yc="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
